# Generated by Django 5.0.4 on 2024-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='dificulty',
            field=models.CharField(choices=[('1', 'Facile'), ('2', 'Moyen'), ('3', 'Difficile'), ('4', 'Exteme')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='lesson',
            name='xp_reward',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='chapiter',
            name='content',
            field=models.TextField(default='Contenue du chapitre', max_length=3000),
        ),
    ]
